In [15]:
import numpy as np

In [16]:
# 1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.
arr = np.array([i for i in range(6)])
type(arr)

numpy.ndarray

In [17]:
# 2. Given a NumPy array 'arr', check if its data type is float64.  arr = np.array([1.5, 2.6, 3.7])
arr = np.array([1.5, 2.6, 3.7])
print(type(arr))
print(arr.dtype)

<class 'numpy.ndarray'>
float64


In [18]:
# 3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
re = [4,3,7]
im = [5,8,9]
arr = np.array([complex(i,j) for i,j in zip(re,im)])
arr

array([4.+5.j, 3.+8.j, 7.+9.j])

In [19]:
# 4. Convert an existing NumPy array 'arr' of integers to float32 data type.
arr = np.array([4,8,10,14])
print(arr.dtype)
arr = arr.astype(np.float32)
print(arr.dtype)

int32
float32


In [20]:
# 5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.
arr = np.array([12.8549732,29.4581236,8.9564712])
print(arr.dtype)
arr = arr.astype(np.float32)
arr

float64


array([12.854973, 29.458124,  8.956471], dtype=float32)

In [21]:
# 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.
def array_attributes(arr):
    print(f"Shape of the array: {arr.shape}")
    print(f"Size of the array: {np.size(arr)}")
    print(f"Data type of the array: {arr.dtype}")
arr1 = np.array([
    [4,6,9],
    [10,2,9],
    [18,7,21],
    [6,25,19]
])
array_attributes(arr1)

Shape of the array: (4, 3)
Size of the array: 12
Data type of the array: int32


In [22]:
# 7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.
def array_dimension(arr):
    print(f"Dimention of the array: {arr.ndim}")
arr1 = np.array([[2, 4], [3,5], [8,9]])
array_dimension(arr1)

Dimention of the array: 2


In [23]:
# 8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.
def item_size_info(arr):
    print(f"Item size: {arr.itemsize}")
    print(f"Total size: {arr.nbytes}")
arr1 = np.array([[3,2,7],[8,4,6],[5,1,9]])
item_size_info(arr1)

Item size: 4
Total size: 36


In [24]:
# 9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.
def array_strides(arr):
    print(f"Strides of the array: {arr.strides}")
arr1 = np.array([[15,21,38,47],[32,48,13,29],[34,27,43,16]])
array_strides(arr1)

Strides of the array: (16, 4)


In [25]:
# 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.
def shape_stride_relationship(arr):
    arr_shape = arr.shape
    arr_itemsize = arr.itemsize
    arr_strides = arr.strides 
    print(arr_shape, arr_itemsize, arr_strides)  
    if arr_strides[0] == arr_shape[1] * arr_itemsize:
        print("Relation established.")
    else:
        print("Relation not established.")
arr1 = arr1 = np.array([
    [4,6,9],
    [10,2,9],
    [18,7,21],
    [6,25,19]
])
shape_stride_relationship(arr1)


(4, 3) 4 (12, 4)
Relation established.


In [26]:
# 11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.
def create_zeros_array(n):
    return np.zeros(n)
create_zeros_array(5)

array([0., 0., 0., 0., 0.])

In [27]:
# 12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.
def create_ones_matrix(m,n):
    return np.ones([m,n])
row = int(input())
col = int(input())
create_ones_matrix(row, col)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
"""
13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified
`step`.
"""
def generate_range_array(st, en, s):
    return np.array([i for i in range(st,en,s)])
start = int(input())
end = int(input())
step = int(input())
generate_range_array(start, end, step)

array([3])

In [29]:
"""
14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
arguments and generates a NumPy array with num equally spaced values between `start` and `stop`(inclusive).
"""
def generate_linear_space(st, sp, n):
    return np.linspace(st, sp, n)
start = float(input())
stop = float(input())
num = int(input())
generate_linear_space(start, stop, num)

array([5., 6., 7.])

In [30]:
"""
15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square
identity matrix of size `n x n` using `numpy.eye`.
"""
def create_identity_matrix(n):
    return np.eye(n)
dim = int(input())
create_identity_matrix(dim)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [31]:
# 16. Write a function that takes a Python list and converts it into a NumPy array.

def create_list(n):
    l0 = []
    for i in range(n):
        n1 = input("enter value: ")
        l0.append(float(n1))
    return l0
n = int(input("insert no of elements of the list: "))
list0 = create_list(n)
np.array(list0)


array([5., 4., 2., 1., 7., 5., 2., 5., 5.])

In [32]:
"""
17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the
same data.
"""
arr = np.array([4,10,8,16,5])
arr1 = arr.view()
arr1[2]=18
print(arr)

[ 4 10 18 16  5]


In [33]:
# 18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.
def array_concatinatination(a1,a2):
    print(f"Concatination: {np.concatenate((a1,a2))}")
arr1 = np.array([4,-2,6,8])
arr2 = np.array([1,7,6,-9])
array_concatinatination(arr1,arr2)


Concatination: [ 4 -2  6  8  1  7  6 -9]


In [34]:
# 19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.
arr1 = np.array([4,-2,6,8])
arr2 = np.array([1,7,6,-9,2,-1])
np.concatenate((arr1,arr2))


array([ 4, -2,  6,  8,  1,  7,  6, -9,  2, -1])

In [35]:
# 20. Write a function that vertically stacks multiple NumPy arrays given as a list.

def v_stack(l_a):
    return np.vstack((l_a))
arr_list = np.array([[18,7,21],[6,25,19], [4,6,9],[10,2,9]])
print(v_stack(arr_list))



[[18  7 21]
 [ 6 25 19]
 [ 4  6  9]
 [10  2  9]]


In [36]:
# 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.

arr = np.random.randint(2,10,(2,3))
arr

array([[5, 5, 4],
       [2, 7, 3]])

In [37]:
# 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

arr = np.linspace(0,1,10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [38]:
# 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

arr = np.logspace(1,1000,5,base=10)
arr

C:\Users\supri\AppData\Roaming\Python\Python312\site-packages\numpy\core\function_base.py:298: RuntimeWarning: overflow encountered in power
  return _nx.power(base, y)


array([1.00000000e+001, 5.62341325e+250,             inf,             inf,
                   inf])

In [39]:
# 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.
import pandas as pd
arr = np.random.randint(1,100,(5,3))
df = pd.DataFrame(data=arr,columns=['A','B','C'])
df


A   B   C
0  91  58  84
1  67  21   8
2  72  62  42
3  92   2  74
4  88  58  80

In [41]:
# 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.

def neg_zero(df):
    arr = np.array(df.T)
    n = int(input())
    arr[n][arr[n] < 0] = 0
    return pd.DataFrame(arr).T
df1 = pd.DataFrame(np.random.randint(-10,10,(6,4)))
neg_zero(df1)

0   1  2  3
0 -4   3 -5  7
1 -5  -5  9  6
2 -8  -6  9  0
3  3 -10 -4  4
4 -5  -5 -7  6
5 -5  -8 -7  9

In [ ]:
"""26. Access the 3rd element from the given NumPy array.
        arr = np.array([10, 20, 30, 40, 50])

"""
arr = np.array([10, 20, 30, 40, 50])
arr[2]

30

In [ ]:
"""
27. Retrieve the element at index (1, 2) from the 2D NumPy array.
        arr_2d = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])
"""
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_2d[1][2]

6

In [ ]:
"""28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
        arr = np.array([3, 8, 2, 10, 5, 7])

"""
arr = np.array([3, 8, 2, 10, 5, 7])
bool_filter = arr > 5
arr[bool_filter]

array([ 8, 10,  7])

In [ ]:
"""29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
        arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
"""
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[2:6]

array([3, 4, 5, 6])

In [ ]:
"""30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.

        arr_2d = np.array([[1, 2, 3],
                          [4, 5, 6],
                          [7, 8, 9]])"""
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_2d[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [ ]:
"""
31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices
provided in another array.
"""
def extract_ele(a1, a2):
    a1_f = a1.flatten()
    return a1_f[a2]
arr1 = np.array([[3,7,-2,5],[8,-4,-9,6]])
arr2 = np.array([1,3,6])
extract_ele(arr1,arr2)
    

array([ 7,  5, -9])

In [ ]:
# 32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.
def filter_threshold(a):
    threshold = int(input())
    return a[a > threshold]
arr = np.random.randint(1,10,(1,6))
print(arr)
print(filter_threshold(arr))

[[6 4 6 6 9 1]]
[9]


In [ ]:
# 33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.
def extract_elements(a,r,c,d):
    return a[r,c,d]
arr_3d = np.random.randint(1,10,(4,4,4))
arr_row = [0,1,3]
arr_col = [0,1,2]
arr_dep = [1,2,3]
print(extract_elements(arr_3d, arr_row, arr_col, arr_dep))

[5 4 4]


In [ ]:
# 34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.
def filter_conditions(a,c1,c2):
    filter = np.logical_and(c1, c2)
    for i in a[filter]:
        print(i)
arr = np.random.randint(0,10,(1,8))
print(arr)
filter_conditions(arr, arr > 2, arr < 8)

[[9 4 8 8 7 3 9 6]]
4
7
3
6


In [ ]:
# 35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.
def extract_elements(a,r,c):
    return a[r,c]
arr_2d = np.random.randint(1,10,(5,5))
arr_row = [1,3]
arr_col = [0,4]
print(arr_2d)
print(extract_elements(arr_2d, arr_row, arr_col))

[[6 3 2 5 4]
 [7 1 1 8 7]
 [5 6 9 5 7]
 [7 8 9 2 4]
 [9 3 4 3 4]]
[7 4]


In [ ]:
# 36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.
arr = np.random.randn(3,3)
print(arr)
print(arr + 5)

[[ 1.44512692  0.67079071  0.68049892]
 [ 0.17908073  1.05662262 -0.65161795]
 [ 1.29860853  1.79338643  1.77301819]]
[[6.44512692 5.67079071 5.68049892]
 [5.17908073 6.05662262 4.34838205]
 [6.29860853 6.79338643 6.77301819]]


In [ ]:
"""
37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the
corresponding element in arr1 using NumPy broadcasting.
"""
arr1 = np.random.randint(1,10,(1,3))
arr2 = np.random.randint(1,10,(4,3))
print(arr1)
print(arr2)
print(arr1 * arr2)

[[7 4 2]]
[[5 2 2]
 [8 8 2]
 [9 2 6]
 [4 4 8]]
[[35  8  4]
 [56 32  4]
 [63  8 12]
 [28 16 16]]


In [ ]:
"""
38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using
NumPy broadcasting.
"""
arr1 = np.random.randint(1,10,(1,4))
arr2 = np.random.randint(1,10,(3,4))
print(arr1)
print(arr2)
print(arr1 + arr2)

[[1 8 4 8]]
[[2 3 6 1]
 [3 2 9 3]
 [5 6 4 5]]
[[ 3 11 10  9]
 [ 4 10 13 11]
 [ 6 14  8 13]]


In [ ]:
"""
39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy
broadcasting.
"""
arr1 = np.random.randint(1,10,(3,1))
arr2 = np.random.randint(1,10,(1,3))
print(arr1)
print(arr2)
print(arr1 + arr2)

[[9]
 [7]
 [5]]
[[2 8 2]]
[[11 17 11]
 [ 9 15  9]
 [ 7 13  7]]


In [ ]:
"""
40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy
broadcasting. Handle the shape incompatibility.
"""
arr1 = np.random.randint(1,10,(2,3))
arr2 = np.random.randint(1,10,(2,2))
print(arr1)
print(arr2)
arr1 = arr1.reshape((1,6))
arr2 = arr2.reshape((4,1))
print(arr1 * arr2)

[[2 9 8]
 [8 1 2]]
[[3 7]
 [3 4]]
[[ 6 27 24 24  3  6]
 [14 63 56 56  7 14]
 [ 6 27 24 24  3  6]
 [ 8 36 32 32  4  8]]


In [ ]:
"""
41. Calculate column-wise mean for the given array:

arr = np.array([[1, 2, 3], [4, 5, 6]])
"""
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.mean(arr, axis=0))

[2.5 3.5 4.5]


In [ ]:
"""42. Find maximum value in each row of the given array:

arr = np.array([[1, 2, 3], [4, 5, 6]])
"""
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.max(arr, axis=1))

[3 6]


In [ ]:
"""43. For the given array, find indices of maximum value in each column.

arr = np.array([[1, 2, 3], [4, 5, 6]])
"""
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.max(arr, axis = 0))

[4 5 6]


In [ ]:
"""44. For the given array, apply custom function to calculate moving sum along rows.

arr = np.array([[1, 2, 3], [4, 5, 6]])
"""
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.cumsum(arr, axis=1))

[[ 1  3  6]
 [ 4  9 15]]


In [ ]:
"""45. In the given array, check if all elements in each column are even.
arr = np.array([[2, 4, 6], [3, 5, 7]])
"""
arr = np.array([[2, 4, 6], [3, 5, 7]])
print(np.all(arr % 2 == 0, axis= 0))

[False False False]


In [ ]:
"""46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the
reshaped matrix.
original_array = np.array([1, 2, 3, 4, 5, 6])

"""
original_array = np.array([1, 2, 3, 4, 5, 6])
reshaprd_array = original_array.reshape(2,3)
print(reshaprd_array)

[[1 2 3]
 [4 5 6]]


In [ ]:
"""47. Create a function that takes a matrix as input and returns the flattened array.
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

"""
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
flattened_array = input_matrix.flatten()
print(flattened_array)

[1 2 3 4 5 6]


In [ ]:
"""48. Write a function that concatenates two given arrays along a specified axis.

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

"""
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
concat_array = np.concatenate((array1, array2))
print(concat_array)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
"""49. Create a function that splits an array into multiple sub-arrays along a specified axis.

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
"""
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.split(original_array,3))

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [ ]:
"""50. Write a function that inserts and then deletes elements from a given array at specified indices.
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]
"""
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]
new_array = np.insert(original_array,indices_to_insert,values_to_insert)
print(new_array)
new_modified_array = np.delete(new_array,indices_to_delete)
print(new_modified_array)

[ 1  2 10  3  4 11  5]
[ 1 10  4 11  5]


In [ ]:
"""51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
Perform element-wise addition between `arr1` and `arr2`.
"""
arr1 = np.random.randint(1,10,(1,10))
arr2 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr1)
print(arr2)
print(arr1 + arr2)

[[3 5 3 2 3 3 9 8 6 6]]
[ 1  2  3  4  5  6  7  8  9 10]
[[ 4  7  6  6  8  9 16 16 15 16]]


In [ ]:
"""52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers
from 1 to 10. Subtract `arr2` from `arr1` element-wise.
"""
arr1 = np.array([10,9,8,7,6,5,4,3,2,1])
arr2 = np.random.randint(1,10,(1,10))
print(arr1)
print(arr2)
print(arr1 - arr2)


[10  9  8  7  6  5  4  3  2  1]
[[6 1 1 7 6 9 2 2 9 9]]
[[ 4  8  7  0  0 -4  2  1 -7 -8]]


In [ ]:
"""53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
Perform element-wise multiplication between `arr1` and `arr2`.
"""
arr1 = np.array([1,2,3,4,5])
arr2 = np.random.randint(1,10,(1,5))
print(arr1)
print(arr2)
print(arr1 * arr2)

[1 2 3 4 5]
[[5 3 9 9 5]]
[[ 5  6 27 36 25]]


In [ ]:
"""54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
to 5. Perform element-wise division of `arr1` by `arr2`.
"""
arr1 = np.array([2,4,6,8,10])
arr2 = np.array([1,2,3,4,5])
print(arr1/arr2)

[2. 2. 2. 2. 2.]


In [ ]:
"""55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.
"""
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,4,3,2,1])
print(arr1 ** arr2)


[ 1 16 27 16  5]


In [ ]:
"""56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
"""
def count_repete(array, string):
    return np.char.count(array, string)
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
count_repete(arr, 'hello')

array([1, 0, 1, 0, 1])

In [ ]:
"""57. Write a function that extracts uppercase characters from a NumPy array of strings.
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
"""
def extract_upper(array):
    return array[np.where(np.char.isupper(array))]
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
extract_upper(arr)

array(['GPT'], dtype='<U6')

In [ ]:
"""58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
"""
def replace_str(array, oldval, newval):
    return np.char.replace(array, old=oldval, new=newval)
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
replace_str(arr,'banana','lemon')

array(['apple', 'lemon', 'grape', 'pineapple'], dtype='<U9')

In [ ]:
"""59. Write a function that concatenates strings in a NumPy array element-wise.
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
"""
def concat_str(a1, a2):
    return np.char.add(arr1, arr2)
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
concat_str(arr1, arr2)

array(['HelloOpen', 'WorldAI'], dtype='<U9')

In [ ]:
"""60. Write a function that finds the length of the longest string in a NumPy array.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
"""
def max_length_str(array):
    arr_lenstr = np.char.str_len(array)
    return np.max(arr_lenstr)
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
max_length_str(arr)

9

In [ ]:
"""61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
standard deviation of the dataset using NumPy's functions.
"""
arr = np.random.randint(1,1000,(1,100))
print(arr)
print(f"Mean: {np.mean(arr)}")
print(f"Median: {np.median(arr)}")
print(f"Varience: {np.var(arr)}")
print(f"Standard Daviation: {np.std(arr)}")

[[ 78 480 294 876 870 640 767 934 270 355 276 625 107 104 358 282 539 219
  449 907 777 384 962 766 746 141   3 194 956 912 460 209 367  51 828 377
   47  15 134 749 509 634 855 333  34 646 898 327 818 403 112 531 514 826
  921 218 906 523 334 669 124  14 351 110 962 904 357 223 754 165 308 674
  719 508 485 238 945 963 130 161 989 986 731 538 523 105 737 365 719  62
  907  20 204 187 243 683 754  90 850 803]]
Mean: 491.1
Median: 482.5
Varience: 95098.99000000002
Standard Daviation: 308.3812413231389


In [ ]:
"""62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the
dataset.
"""
arr = np.random.randint(1,100,(1,50))
print(arr)
print(f"25th percentile: {np.percentile(arr, 25)}")
print(f"25th percentile: {np.percentile(arr, 5)}")

[[76  8 36 49 47  7 33  4 57  9 43  8 36 69 45 84 83  5 74 71 73 27 91 54
  79 22 41 63 48  1 55 89 34 71 31 59 12 64 87 33 61 25 84 17 47 65  8 20
  43 65]]
25th percentile: 25.5
25th percentile: 5.9


In [ ]:
"""63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these
arrays using NumPy's `corrcoef` function.

"""
arr1 = np.random.randint(1,10,(1,10))
arr2 = np.random.randint(1,10,(1,10))
print(arr1)
print(arr2)
print(np.corrcoef(arr1, arr2))


[[2 2 4 3 3 3 4 6 3 2]]
[[7 3 4 8 1 7 9 5 6 5]]
[[1.         0.07484812]
 [0.07484812 1.        ]]


In [ ]:
"""64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.

"""
arr1 = np.random.randint(1,10,(3,2))
arr2 = np.random.randint(1,10,(2,3))
print(np.dot(arr1, arr2))

[[39 46 23]
 [68 79 40]
 [25 56 17]]


In [ ]:
"""65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th
percentiles along with the first and third quartiles.
"""
arr = np.random.randint(10,1000,(1,50))
print(arr)
print(f"10th percentile: {np.percentile(arr, 10)}")
print(f"1st quartile: {np.percentile(arr, 25)}")
print(f"50th percentile: {np.median(arr)}")
print(f"3rd quartile: {np.percentile(arr, 75)}")
print(f"90th percentile: {np.percentile(arr, 90)}")

[[283 610  87 861 367 311 576 789 402 951 550 593 559 151 366 215 813 868
  707 849 127 332 957 438 790 473 965 255 565 760 156 210 288 435 737 505
  236 843 780 396 601 305 273 264 887  58 863 453 450 870]]
10th percentile: 204.60000000000002
1st quartile: 292.25
50th percentile: 489.0
3rd quartile: 786.75
90th percentile: 868.2


In [ ]:
"""66. Create a NumPy array of integers and find the index of a specific element.
"""
arr = np.array([6,8,3,1,9,2,5,10,7,4])
print(np.where(arr == 5))

(array([6], dtype=int64),)


In [ ]:
"""67. Generate a random NumPy array and sort it in ascending order"""
arr = np.random.randint(1,50,(1,20))
print(arr)
np.sort(arr)

[[41 28 22 16 19 38  4 49 38 28 22 35 49 17 25 11 28  5  4 23]]


array([[ 4,  4,  5, 11, 16, 17, 19, 22, 22, 23, 25, 28, 28, 28, 35, 38,
        38, 41, 49, 49]])

In [ ]:
"""68. Filter elements >20 in the given NumPy array.
arr = np.array([12, 25, 6, 42, 8, 30])
"""
arr = np.array([12, 25, 6, 42, 8, 30])
print(arr[np.where(arr > 20)])

[25 42 30]


In [ ]:
"""69. Filter elements which are divisible by 3 from a given NumPy array.
arr = np.array([1, 5, 8, 12, 15])
"""
arr = np.array([1, 5, 8, 12, 15])
print(arr[np.where(arr % 3 == 0)])

[12 15]


In [ ]:
"""70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
arr = np.array([10, 20, 30, 40, 50])
"""
arr = np.array([10, 20, 30, 40, 50])
print(arr[np.where(np.all((arr >= 20, arr <= 40), axis=0))])

[20 30 40]


In [ ]:
"""71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
arr = np.array([1, 2, 3])
"""
arr = np.array([1, 2, 3])
print(arr.dtype.byteorder)

=


In [ ]:
"""72. For the given NumPy array, perform byte swapping in place using `byteswap()`.
arr = np.array([1, 2, 3], dtype=np.int32)
"""
arr = np.array([1, 2, 3], dtype=np.int32)
print(arr.byteswap())

[16777216 33554432 50331648]


In [ ]:
"""73. For the given NumPy array, swap its byte order without modifying the original array using
`newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)
"""
arr = np.array([1, 2, 3], dtype=np.int32)
print(arr.newbyteorder())

[16777216 33554432 50331648]


In [ ]:
"""74. For the given NumPy array and swap its byte order conditionally based on system endianness using
`newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)
"""
arr = np.array([1, 2, 3], dtype=np.int32)
print(arr.newbyteorder())

[16777216 33554432 50331648]


In [ ]:
"""76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify
an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

"""
arr = np.array([2,4,7,5,6,3,1,9,10,8])
arr1 = arr.copy()
arr1[4] = 15
print(arr)
print(arr1)

[ 2  4  7  5  6  3  1  9 10  8]
[ 2  4  7  5 15  3  1  9 10  8]


In [ ]:
"""77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.
"""
matrix = np.random.randint(1,10,(3,3))
view_slice = matrix[0:2, 1:3]
print(matrix)
print(view_slice)
view_slice[1][0] = 15
print(view_slice)
print(matrix)

[[7 4 4]
 [6 9 7]
 [5 5 7]]
[[4 4]
 [9 7]]
[[ 4  4]
 [15  7]]
[[ 7  4  4]
 [ 6 15  7]
 [ 5  5  7]]


In [ ]:
"""78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
`view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.
"""
array_a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
view_b = array_a[1:4,0:2]
print(view_b)
view_b = view_b + 5
print(view_b)
print(array_a)

[[ 4  5]
 [ 7  8]
 [10 11]]
[[ 9 10]
 [12 13]
 [15 16]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
"""79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
`reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
reflects changes in the original `orig_array`.
"""
orig_array = np.array([[1,2,3,4],[5,6,7,8]])
reshaped_view = orig_array.reshape(4,2)
print(reshaped_view)
reshaped_view[1][1] = 10
print(reshaped_view)
print(orig_array)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[ 1  2]
 [ 3 10]
 [ 5  6]
 [ 7  8]]
[[ 1  2  3 10]
 [ 5  6  7  8]]


In [ ]:
"""80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.
"""
data = np.random.randint(1,10,(3,4))
print(data)
data_copy = data[np.where(data > 5)]
print(data_copy)
data_copy[2] = 20
print(data_copy)
print(data)

[[1 4 7 2]
 [9 7 1 1]
 [6 9 5 5]]
[7 9 7 6 9]
[ 7  9 20  6  9]
[[1 4 7 2]
 [9 7 1 1]
 [6 9 5 5]]


In [ ]:
"""81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction
operations between them.
"""
A = np.random.randint(1,20,(3,4))
B = np.random.randint(1,20,(3,4))
print(A)
print(B)
print(f"A + B = {A + B}")
print(f"A - B = {A - B}")

[[ 2  3  2 14]
 [17  8  2  4]
 [ 5 12  2 19]]
[[ 7 15  5  7]
 [17  3  7 19]
 [12 17  4  7]]
A + B = [[ 9 18  7 21]
 [34 11  9 23]
 [17 29  6 26]]
A - B = [[ -5 -12  -3   7]
 [  0   5  -5 -15]
 [ -7  -5  -2  12]]


In [ ]:
"""82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.
"""
C = np.random.randint(1,20,(3,2))
D = np.random.randint(1,20,(2,4))
print(C)
print(D)
print(np.dot(C,D))

[[ 5  7]
 [15  3]
 [18  4]]
[[ 4 19 18  3]
 [ 3  2 18  2]]
[[ 41 109 216  29]
 [ 69 291 324  51]
 [ 84 350 396  62]]


In [ ]:
"""83. Create a matrix `E` and find its transpose.
"""
E = np.random.randint(1,20,(3,2))
print(E)
print(E.T)

[[ 8 10]
 [13  3]
 [17 13]]
[[ 8 13 17]
 [10  3 13]]


In [44]:
"""84. Generate a square matrix `F` and compute its determinant.
"""
F = np.random.randint(1,20,(3,3))
print(np.linalg.det(F))

4171.999999999998


In [45]:
"""85. Create a square matrix `G` and find its inverse.
"""
G = np.random.randint(1,20,(3,3))
print(G)
print(np.linalg.inv(G))

[[13  8  1]
 [ 8  7 18]
 [ 3 18  9]]
[[ 0.07644991  0.01581722 -0.04012888]
 [ 0.00527241 -0.03339192  0.06619801]
 [-0.03602812  0.06151142 -0.00790861]]
